### PR TITLE
feat(dict): Whitelist Kanji Learner's Dictionary 2nd Edition

### LINKED ISSUE #1363: Add support for Kanji Learner's Dictionary 2nd Edition indices to rikaikun
This is in kanji dictionary data so I just need to whitelist it:
http://www.edrdg.org/wiki/index.php/KANJIDIC_Project#:~:text=Kanji%20Learners%20Dictionary%20number%20(2nd%20ed)

### PR DESCRIPTION
**Pull request by tora-pan**
Whitelist Kanji Learner's Dictionary 2nd Edition.

Add required info to the `kanjiInfo` and `kanjiInfoLabelList` in their respective files.

Needs update to entries in `kanji.dat` file to include KLD 2nd Edition info.

Fixes #1363

### CODE REVIEW

**Review by melink14 — CHANGES_REQUESTED** [review]
Looks good to me, though I realize now I don't have any visual tests of the options page so I don't really know how this shows up...

Did you test manually?

For submission I think we should wait until after the monday regular update and then update the dictionary updating util to populate the DL reference and then submit with the new kanji dat file only.

**Review by melink14 — CHANGES_REQUESTED** [review]
Can you run the script and upload only the kanji data files as well?

We don't want the changes casued by this PR to show up in an unrelated PR later since that will make tracing changes harder in the past.

You'll find most of the effort we take in constructing commits and PRs is all to make understanding the logic and reasoning of the codebase easier for our future selves. :)

**Comment by tora-pan** [comment]
I think everything went well. 

ran `npm run update-db` and this was the output.
```
Fetching word dictionary...
Parsing dictionary created: 2023-03-13
Writing index...
Fetching names dictionary...
Parsing dictionary created: 2023-03-13
Writing index...
Fetching kanji dictionaries...
Parsing KANJIDIC dictionary from 2023-03-13
Parsing KANJD212 dictionary from 2023-03-13
Done.
```
Did A quick scan over the file and it looks like it worked correctly. May rows contain the `DL####` number now.

Will push changes now.

**Review by melink14 — CHANGES_REQUESTED** [review]
Two things:

1. To re-iterate from my last question: did you test this manually selecting and deselecting the new index from options. Since there are no tests for options, we should do a bit of testing first.

2. I noticed this still said it was waiting on changes to be made but you can't resolve the top level review comment like this. I'd say once you're 'waiting' you should click the 're-request review' button to passit back to me.

**Comment by tora-pan** [comment]
Sorry about that. 

Yes it has been tested.
Screenshot 2023-03-19 at 5 34 35 PM

**Comment by melink14** [comment]
More than the kanji view (which has automated testing) I was curious about
the options page which lacks visual tests.

Just to double-check, I assume it appears and works there too?

2023年3月20日(月) 9:40 Travis Pandos ***@***.***>:

**Comment by tora-pan** [comment]
yep, I tested by toggling it on and off.

**Comment by tora-pan** [comment]
I'll send more screenshots or a mini video later 👍

**Review by melink14 — APPROVED** [review]

**Comment by melink14** [comment]
Just as a note to future readers: I meant to edit the PR title before merge to something a bit more specific but forgot. Luckily it was already pretty good!

**Comment by melink14** [comment]
@all-contributors Add @tora-pan for code.

**Pull request merged**
